<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "at_vslider"
 *
 * Auto generated by Extension Builder 2020-08-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'AshokaTree Vertical Slider',
    'description' => 'Responsive vertical slider with Title, Link, Subtitle, Description, Image.',
    'category' => 'plugin',
    'author' => 'Nirmalya Mondal',
    'author_email' => 'nirmalya.mondal@gmail.com',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => 'uploads/tx_atvslider/',
    'clearCacheOnLoad' => 0,
    'version' => '10.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
